import {
  Camera, Utensils, Flower2, Building2, Music, Zap,
  Lightbulb, Sparkles, Car, Heart, Handshake, Palette,
  Mic, PartyPopper, Tent, type LucideIcon
} from 'lucide-react';

export type CategoryDef = {
  label: string;
  icon: LucideIcon;
  color: string;
  gradient: string;
  description: string;
  longDescription: string;
  whatTheyDo: string[];
  startingPrice: string;
  image: string;
};

export const CATEGORIES: CategoryDef[] = [
  {
    label: 'Photographer',
    icon: Camera,
    color: 'sage',
    gradient: 'from-sage-500 to-sage-700',
    description: 'Capture every smile, tear, and dance move with award-winning photographers.',
    longDescription: 'Professional photographers who specialize in weddings, events, portraits, and candid moments. They bring high-end equipment, creative direction, and years of experience to ensure your memories are preserved beautifully.',
    whatTheyDo: [
      'Candid and traditional wedding photography',
      'Pre-wedding and engagement shoots',
      'Event coverage with multiple photographers',
      'Drone aerial photography',
      'Same-day edited preview photos',
      'Premium photo albums and prints',
    ],
    startingPrice: '₹15,000',
    image: '',
  },
  {
    label: 'Decorator',
    icon: Flower2,
    color: 'cream',
    gradient: 'from-cream-500 to-cream-700',
    description: 'Transform any venue into a breathtaking celebration space.',
    longDescription: 'Decorators bring your vision to life with floral arrangements, stage setups, lighting design, themed decor, and table settings. From intimate gatherings to grand weddings, they handle every visual detail.',
    whatTheyDo: [
      'Stage and mandap decoration',
      'Floral arrangements and centerpieces',
      'Theme-based event decor',
      'Lighting and ambiance design',
      'Entrance and walkway setups',
      'Table setting and chair covers',
    ],
    startingPrice: '₹10,000',
    image: '',
  },
  {
    label: 'Tent House',
    icon: Tent,
    color: 'sage',
    gradient: 'from-sage-600 to-sage-800',
    description: 'Tents, canopies, and structural setups for outdoor and indoor events.',
    longDescription: 'Tent house providers supply tents, marquees, pandals, seating arrangements, and structural setups. Essential for outdoor weddings, community events, and large gatherings that need weather protection and organized spaces.',
    whatTheyDo: [
      'Tent and marquee setup',
      'Pandal and canopy structures',
      'Seating arrangement (chairs, tables, sofas)',
      'Stage platform construction',
      'Carpet and flooring installation',
      'Dismantling after the event',
    ],
    startingPrice: '₹8,000',
    image: '',
  },
  {
    label: 'DJ',
    icon: Music,
    color: 'sage',
    gradient: 'from-sage-500 to-sage-700',
    description: 'Keep the party alive with professional DJs and sound systems.',
    longDescription: 'DJs bring the energy with curated playlists, professional sound systems, lighting effects, and crowd engagement. They read the room and keep guests dancing all night long.',
    whatTheyDo: [
      'Live DJ performance with curated playlists',
      'Professional sound system setup',
      'LED and laser lighting effects',
      'MC services and crowd engagement',
      'Bollywood, regional, and international music',
      'Karaoke and special request handling',
    ],
    startingPrice: '₹12,000',
    image: '',
  },
  {
    label: 'Catering',
    icon: Utensils,
    color: 'cream',
    gradient: 'from-cream-500 to-cream-700',
    description: 'Gourmet menus for every taste — from traditional feasts to fusion cuisine.',
    longDescription: 'Catering services provide complete food and beverage solutions including menu planning, live counters, multi-cuisine options, serving staff, and presentation. They handle everything from appetizers to desserts.',
    whatTheyDo: [
      'Multi-cuisine menu planning (veg & non-veg)',
      'Live food counters (chaat, dosa, pasta)',
      'Professional serving staff and waiters',
      'Beverage and bar services',
      'Dessert and cake stations',
      'Hygiene and food safety compliance',
    ],
    startingPrice: '₹150/plate',
    image: '',
  },
  {
    label: 'Lights',
    icon: Lightbulb,
    color: 'gold',
    gradient: 'from-gold-500 to-gold-700',
    description: 'Professional lighting design that sets the perfect mood.',
    longDescription: 'Lighting specialists provide ambient, decorative, and stage lighting solutions. From fairy lights to grand illumination setups, they create the perfect atmosphere for your celebration.',
    whatTheyDo: [
      'Ambient and mood lighting design',
      'Stage and spotlight setup',
      'LED wall and backdrop lighting',
      'Fairy light and string installations',
      'Dance floor lighting effects',
      'Power backup and electrical safety',
    ],
    startingPrice: '₹7,000',
    image: '',
  },
  {
    label: 'Makeup',
    icon: Sparkles,
    color: 'cream',
    gradient: 'from-cream-600 to-cream-800',
    description: 'Look your absolute best with professional makeup artists.',
    longDescription: 'Makeup artists specialize in bridal makeup, party looks, HD makeup, airbrush techniques, and draping. They use premium products and ensure you look flawless for every photo and video.',
    whatTheyDo: [
      'Bridal HD and airbrush makeup',
      'Party and engagement makeup',
      'Saree draping and styling',
      'Hairstyling and accessories',
      'Pre-bridal skincare consultation',
      'Trial sessions before the event',
    ],
    startingPrice: '₹5,000',
    image: '',
  },
  {
    label: 'Travel',
    icon: Car,
    color: 'sage',
    gradient: 'from-sage-600 to-sage-800',
    description: 'Comfortable transportation for guests and the wedding party.',
    longDescription: 'Travel providers offer cars, buses, and luxury vehicles for guest transportation, bride/groom arrivals, and venue transfers. They ensure everyone arrives on time and in comfort.',
    whatTheyDo: [
      'Luxury car rentals for bride & groom',
      'Guest transportation (buses, tempo travellers)',
      'Airport pickup and drop services',
      'Vintage and decorated car options',
      'Multi-venue transport coordination',
      'Experienced drivers with local knowledge',
    ],
    startingPrice: '₹3,000',
    image: '',
  },
  {
    label: 'Wedding Hall',
    icon: Building2,
    color: 'sage',
    gradient: 'from-sage-500 to-sage-700',
    description: 'Stunning venues from heritage palaces to modern banquet halls.',
    longDescription: 'Wedding halls and venues provide the perfect backdrop for your celebration. Options range from intimate spaces to grand banquet halls, outdoor gardens, heritage properties, and destination venues.',
    whatTheyDo: [
      'Banquet hall and lawn rentals',
      'Heritage palace and destination venues',
      'In-house catering and decoration options',
      'Parking and valet services',
      'Bridal rooms and guest lounges',
      'AC/non-AC options with capacity flexibility',
    ],
    startingPrice: '₹50,000',
    image: '',
  },
  {
    label: 'Pandit',
    icon: Handshake,
    color: 'gold',
    gradient: 'from-gold-500 to-gold-700',
    description: 'Experienced priests to conduct ceremonies with authenticity.',
    longDescription: 'Pandits and priests conduct weddings, pujas, and religious ceremonies with proper Vedic rituals. They guide families through every step, ensuring traditions are honored and ceremonies are meaningful.',
    whatTheyDo: [
      'Wedding ceremony (Vedic rituals)',
      'Engagement and sagai ceremonies',
      'Griha pravesh and housewarming pujas',
      'Satyanarayan katha and havan',
      'Muhurat guidance and astrology',
      'Regional and community-specific rituals',
    ],
    startingPrice: '₹5,100',
    image: '',
  },
  {
    label: 'Mehendi Artist',
    icon: Palette,
    color: 'cream',
    gradient: 'from-cream-500 to-cream-700',
    description: 'Intricate henna designs for brides and guests alike.',
    longDescription: 'Mehendi artists create stunning henna designs ranging from traditional Indian patterns to contemporary Arabic and fusion styles. They use organic henna and ensure long-lasting, deep stains.',
    whatTheyDo: [
      'Bridal mehendi (full hand and arm)',
      'Guest mehendi stations at events',
      'Arabic, Rajasthani, and fusion designs',
      'Organic henna with essential oils',
      'Glitter and colored henna options',
      'Mehendi cones for DIY application',
    ],
    startingPrice: '₹1,500',
    image: '',
  },
  {
    label: 'Flower Decor',
    icon: Flower2,
    color: 'sage',
    gradient: 'from-sage-600 to-sage-800',
    description: 'Fresh floral arrangements that add elegance to every occasion.',
    longDescription: 'Flower decor specialists create stunning arrangements using fresh flowers — from marigold and rose to exotic imports. They handle mandap flowers, table centerpieces, garlands, and floral arches.',
    whatTheyDo: [
      'Mandap and stage flower decoration',
      'Bridal and groom floral accessories',
      'Table centerpieces and bouquets',
      'Floral arches and entrance decor',
      'Flower walls and backdrops',
      'Garlands and boutonnieres',
    ],
    startingPrice: '₹12,000',
    image: '',
  },
  {
    label: 'Anchor',
    icon: Mic,
    color: 'gold',
    gradient: 'from-gold-500 to-gold-700',
    description: 'Charismatic hosts who keep your event flowing with energy.',
    longDescription: 'Anchors and emcees host your event with charm, humor, and professionalism. They manage the timeline, engage the audience, introduce speakers, and ensure the celebration runs smoothly from start to finish.',
    whatTheyDo: [
      'Wedding and sangeet hosting',
      'Corporate event MC services',
      'Audience games and interactive activities',
      'Bilingual and multilingual hosting',
      'Script writing and event flow planning',
      'Coordination with DJs and performers',
    ],
    startingPrice: '₹8,000',
    image: '',
  },
  {
    label: 'Band',
    icon: PartyPopper,
    color: 'sage',
    gradient: 'from-sage-500 to-sage-700',
    description: 'Live bands and musicians to make your celebration unforgettable.',
    longDescription: 'Live bands perform Bollywood hits, regional favorites, Sufi, jazz, and fusion music. They bring energy and entertainment that recorded music simply cannot match, creating memorable moments for guests.',
    whatTheyDo: [
      'Live band performance (4-8 musicians)',
      'Bollywood and regional music sets',
      'Sufi and classical fusion performances',
      'Instrumental and acoustic sets',
      'Custom song requests and dedications',
      'Sound and instrument setup',
    ],
    startingPrice: '₹20,000',
    image: '',
  },
];

export const CATEGORY_LABELS = CATEGORIES.map(c => c.label);

export function getCategory(label: string): CategoryDef | undefined {
  return CATEGORIES.find(c => c.label === label);
}
